text = '''<link rel="stylesheet" href="../assets/css/ImYZFSkiVugcEWTPoTxdj.css">
<link rel="stylesheet" href="../assets/css/nsSXpZKZdshcPtXU.css">
<link rel="stylesheet" href="../assets/css/nrilLfYGPrjUVFuDQ.css">
<link rel="stylesheet" href="../assets/css/oCgixdRdJVzZMecY.css">
<link rel="stylesheet" href="../assets/css/CZNfoZDbVizxJvPUkVRl.css">
<link rel="stylesheet" href="../assets/css/TXFPVbdMwrMxYTxXg.css">
<link rel="stylesheet" href="../assets/css/FPIMWIiomHXrRidGC.css">
<link rel="stylesheet" href="../assets/css/{chHTfrXajhrfCNqU.css">
<link rel="stylesheet" href="../assets/css/SedJZakJuDhyDPKEbe.css">
<link rel="stylesheet" href="../assets/css/FWwjPsYfqBYPilMY.css">
<link rel="stylesheet" href="../assets/css/oNFawIjgJIckuMQFtmK.css">
<link rel="stylesheet" href="../assets/css/YvASvYMqLkhtcFrit.css">
<link rel="stylesheet" href="../assets/css/QRNKbSPAyWIlfvBlkj.css">
<link rel="stylesheet" href="../assets/css/DMklHksgxIYQMark.css">
<link rel="stylesheet" href="../assets/css/EiVAGSsBSapVieQVMjlzA.css">
<link rel="stylesheet" href="../assets/css/IjdqiNzCsesZBMJtNvq.css">
<link rel="stylesheet" href="../assets/css/aebmKLECaLKwTCkGFTux.css">
<link rel="stylesheet" href="../assets/css/IytAotyWzPkyagkD.css">
<link rel="stylesheet" href="../assets/css/pjmIhPqyGsuJQxfGxGhJo.css">
<link rel="stylesheet" href="../assets/css/trIOtzyHkVedgFkU.css">
<link rel="stylesheet" href="../assets/css/SWrdwDFKGWYbgiBSxqPx.css">
<link rel="stylesheet" href="../assets/css/dzxXGpyzrLygZCxY.css">
<link rel="stylesheet" href="../assets/css/XgOGGmpWTDZQBrSOYE.css">
<link rel="stylesheet" href="../assets/css/tQzZgFxlnkWCnGbkgTw.css">
<link rel="stylesheet" href="../assets/css/zJQfcLndpqhmPVcwmJu.css">
<link rel="stylesheet" href="../assets/css/ZcKRmFhGjcwTqkxxy.css">
<link rel="stylesheet" href="../assets/css/svZaEerAGLKFWieVfTAr.css">
<link rel="stylesheet" href="../assets/css/ezayiEFQmffTPXHexp.css">
<link rel="stylesheet" href="../assets/css/NVxRfDzCykwSCPSHKhl.css">
<link rel="stylesheet" href="../assets/css/uDEvdDRYgyYhUNLqCXPS.css">
<link rel="stylesheet" href="../assets/css/nAjapDyPboYSShglLOky.css">
<link rel="stylesheet" href="../assets/css/QFpZXgoEXKpDaALurvyI.css">
<link rel="stylesheet" href="../assets/css/uvhUkHfNMDUUAnru.css">
<link rel="stylesheet" href="../assets/css/gHKnWTxDZkRQkDKK.css">
<link rel="stylesheet" href="../assets/css/QWoxqerDGbjyoPSEKO.css">
<link rel="stylesheet" href="../assets/css/yGRheLKZOEXBCjxUbcrW.css">
<link rel="stylesheet" href="../assets/css/IAFQgTMmicphyyUeqqm.css">
<link rel="stylesheet" href="../assets/css/CiWBpIpihRBUOHjeWG.css">
<link rel="stylesheet" href="../assets/css/uaFqAAsWbGIQhsdzHv.css">
<link rel="stylesheet" href="../assets/css/vpndcdMQAfhGVfcKaKjP.css">
<link rel="stylesheet" href="../assets/css/}gSlONKovZIDohUxuU.css">
'''.split('\n')
print ''.join([t[43:44] for t in text])